export default {
  state: {
    dataUsers: [{
      "id": "u0002",
      "username": "Son"
    }, {
      "id": "u0003",
      "username": "Bren"
    }, {
      "id": "u0004",
      "username": "Baxy"
    }, {
      "id": "u0005",
      "username": "Ives"
    }, {
      "id": "u0006",
      "username": "Ewan"
    }, {
      "id": "u0007",
      "username": "Munmro"
    }, {
      "id": "u0008",
      "username": "Judah"
    }, {
      "id": "u0009",
      "username": "Arvin"
    }, {
      "id": "u00010",
      "username": "Nathanil"
    }, {
      "id": "u00011",
      "username": "Robin"
    }, {
      "id": "u00012",
      "username": "Barnabas"
    }, {
      "id": "u00013",
      "username": "Odell"
    }, {
      "id": "u00014",
      "username": "Arlen"
    }, {
      "id": "u00015",
      "username": "Allard"
    }, {
      "id": "u00016",
      "username": "Sollie"
    }, {
      "id": "u00017",
      "username": "Cale"
    }, {
      "id": "u00018",
      "username": "Uriah"
    }, {
      "id": "u00019",
      "username": "Irving"
    }, {
      "id": "u00020",
      "username": "Moses"
    }, {
      "id": "u00021",
      "username": "Benedetto"
    }, {
      "id": "u00022",
      "username": "Burnaby"
    }, {
      "id": "u00023",
      "username": "Carrol"
    }, {
      "id": "u00024",
      "username": "Dannie"
    }, {
      "id": "u00025",
      "username": "Mead"
    }, {
      "id": "u00026",
      "username": "Kerry"
    }, {
      "id": "u00027",
      "username": "Hilly"
    }, {
      "id": "u00028",
      "username": "Reynard"
    }, {
      "id": "u00029",
      "username": "Launce"
    }, {
      "id": "u00030",
      "username": "Culley"
    }, {
      "id": "u00031",
      "username": "Otto"
    }, {
      "id": "u00032",
      "username": "Hyman"
    }, {
      "id": "u00033",
      "username": "Vidovik"
    }, {
      "id": "u00034",
      "username": "Pascale"
    }, {
      "id": "u00035",
      "username": "Terencio"
    }, {
      "id": "u00036",
      "username": "Smitty"
    }, {
      "id": "u00037",
      "username": "Zach"
    }, {
      "id": "u00038",
      "username": "Perceval"
    }, {
      "id": "u00039",
      "username": "Jared"
    }, {
      "id": "u00040",
      "username": "Car"
    }, {
      "id": "u00041",
      "username": "Ervin"
    }, {
      "id": "u00042",
      "username": "Niki"
    }, {
      "id": "u00043",
      "username": "Jerrold"
    }, {
      "id": "u00044",
      "username": "Benton"
    }, {
      "id": "u00045",
      "username": "Reed"
    }, {
      "id": "u00046",
      "username": "Mendy"
    }, {
      "id": "u00047",
      "username": "Abrahan"
    }, {
      "id": "u00048",
      "username": "Alexander"
    }, {
      "id": "u00049",
      "username": "Sigvard"
    }, {
      "id": "u00050",
      "username": "Brewer"
    }, {
      "id": "u00051",
      "username": "Gunar"
    }, {
      "id": "u00052",
      "username": "Alanson"
    }, {
      "id": "u00053",
      "username": "Jim"
    }, {
      "id": "u00054",
      "username": "Herculie"
    }, {
      "id": "u00055",
      "username": "Nicko"
    }, {
      "id": "u00056",
      "username": "Tull"
    }, {
      "id": "u00057",
      "username": "Gabriel"
    }, {
      "id": "u00058",
      "username": "Elwin"
    }, {
      "id": "u00059",
      "username": "Kort"
    }, {
      "id": "u00060",
      "username": "Niki"
    }, {
      "id": "u00061",
      "username": "Garrard"
    }, {
      "id": "u00062",
      "username": "Maury"
    }, {
      "id": "u00063",
      "username": "Trefor"
    }, {
      "id": "u00064",
      "username": "Allard"
    }, {
      "id": "u00065",
      "username": "Frederigo"
    }, {
      "id": "u00066",
      "username": "Fee"
    }, {
      "id": "u00067",
      "username": "Rolf"
    }, {
      "id": "u00068",
      "username": "Giacomo"
    }, {
      "id": "u00069",
      "username": "Jareb"
    }, {
      "id": "u00070",
      "username": "Otis"
    }, {
      "id": "u00071",
      "username": "Guido"
    }, {
      "id": "u00072",
      "username": "Martie"
    }, {
      "id": "u00073",
      "username": "Beniamino"
    }, {
      "id": "u00074",
      "username": "Franz"
    }, {
      "id": "u00075",
      "username": "Land"
    }, {
      "id": "u00076",
      "username": "Miguel"
    }, {
      "id": "u00077",
      "username": "Winfield"
    }, {
      "id": "u00078",
      "username": "Julie"
    }, {
      "id": "u00079",
      "username": "Tobiah"
    }, {
      "id": "u00080",
      "username": "Peterus"
    }, {
      "id": "u00081",
      "username": "Trent"
    }, {
      "id": "u00082",
      "username": "Esdras"
    }, {
      "id": "u00083",
      "username": "Sheppard"
    }, {
      "id": "u00084",
      "username": "Gaylor"
    }, {
      "id": "u00085",
      "username": "Saundra"
    }, {
      "id": "u00086",
      "username": "Dagny"
    }, {
      "id": "u00087",
      "username": "Charlie"
    }, {
      "id": "u00088",
      "username": "Conan"
    }, {
      "id": "u00089",
      "username": "Madison"
    }, {
      "id": "u00090",
      "username": "Wake"
    }, {
      "id": "u00091",
      "username": "Horst"
    }, {
      "id": "u00092",
      "username": "Connie"
    }, {
      "id": "u00093",
      "username": "Demetri"
    }, {
      "id": "u00094",
      "username": "Gun"
    }, {
      "id": "u00095",
      "username": "Emery"
    }, {
      "id": "u00096",
      "username": "Lalo"
    }, {
      "id": "u00097",
      "username": "Alexis"
    }, {
      "id": "u00098",
      "username": "Pippo"
    }, {
      "id": "u00099",
      "username": "Benedicto"
    }, {
      "id": "u000100",
      "username": "Billy"
    }, {
      "id": "u000101",
      "username": "Marwin"
    }],
    dataGroups: [
      {id: 'g123456', name: 'People', users: ['u0002', 'u0003', 'u0004']},
      {id: 'g123457', name: 'Ork`s', users: ['u0002', 'u0006', 'u0007']},
      {id: 'g123458', name: 'Dark Elf', users: ['u0008', 'u0009', 'u00010', 'u00011', 'u00012', 'u00013', 'u00014']},
      {id: 'g123459', name: 'Light Elf', users: []}
    ]
  },
  mutations: {
    removeG (state, id) {
      state.dataGroups = state.dataGroups.filter((group) => group.id !== id)
    },
    addG (state, payload) {
      state.dataGroups.push({
        id: payload.id,
        name: payload.name,
        users: []
      })
    },
  },
  actions: {
    removeGroup (context, id) {
      context.commit('removeG', id);
    },
    addGroup (context, payload) {
      context.commit('addG', payload);
    },
  },
  getters: {
    dataUsers(state) {
      return state.dataUsers
    },
    dataGroups(state) {
      return state.dataGroups
    }
  }
}